# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PilSim(object):
    def setupUi(self, PilSim):
        PilSim.setObjectName("PilSim")
        PilSim.resize(441, 397)
        PilSim.setMinimumSize(QtCore.QSize(354, 346))
        PilSim.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(PilSim)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.waypoint_file_enable = QtWidgets.QCheckBox(self.centralwidget)
        self.waypoint_file_enable.setObjectName("waypoint_file_enable")
        self.horizontalLayout_7.addWidget(self.waypoint_file_enable)
        self.waypoint_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.waypoint_file_button.setObjectName("waypoint_file_button")
        self.horizontalLayout_7.addWidget(self.waypoint_file_button)
        self.waypoint_file_label = QtWidgets.QLabel(self.centralwidget)
        self.waypoint_file_label.setText("")
        self.waypoint_file_label.setObjectName("waypoint_file_label")
        self.horizontalLayout_7.addWidget(self.waypoint_file_label)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.log_file_enable = QtWidgets.QCheckBox(self.centralwidget)
        self.log_file_enable.setChecked(True)
        self.log_file_enable.setObjectName("log_file_enable")
        self.horizontalLayout_10.addWidget(self.log_file_enable)
        self.log_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.log_file_button.setObjectName("log_file_button")
        self.horizontalLayout_10.addWidget(self.log_file_button)
        self.log_file_label = QtWidgets.QLabel(self.centralwidget)
        self.log_file_label.setText("")
        self.log_file_label.setObjectName("log_file_label")
        self.horizontalLayout_10.addWidget(self.log_file_label)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.telemetry_rate_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.telemetry_rate_box.setMinimum(0.5)
        self.telemetry_rate_box.setMaximum(10.0)
        self.telemetry_rate_box.setProperty("value", 10.0)
        self.telemetry_rate_box.setObjectName("telemetry_rate_box")
        self.horizontalLayout_8.addWidget(self.telemetry_rate_box)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.usb_port_box_to_arduino = QtWidgets.QComboBox(self.centralwidget)
        self.usb_port_box_to_arduino.setObjectName("usb_port_box_to_arduino")
        self.horizontalLayout.addWidget(self.usb_port_box_to_arduino)
        self.refresh_ports = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_ports.setObjectName("refresh_ports")
        self.horizontalLayout.addWidget(self.refresh_ports)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.usb_port_box_from_arduino = QtWidgets.QComboBox(self.centralwidget)
        self.usb_port_box_from_arduino.setObjectName("usb_port_box_from_arduino")
        self.horizontalLayout_17.addWidget(self.usb_port_box_from_arduino)
        self.refresh_ports_2 = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_ports_2.setObjectName("refresh_ports_2")
        self.horizontalLayout_17.addWidget(self.refresh_ports_2)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.pilsim_enable = QtWidgets.QCheckBox(self.centralwidget)
        self.pilsim_enable.setObjectName("pilsim_enable")
        self.horizontalLayout_11.addWidget(self.pilsim_enable)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pitch_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pitch_box.setMinimum(-180.0)
        self.pitch_box.setMaximum(180.0)
        self.pitch_box.setProperty("value", 10.0)
        self.pitch_box.setObjectName("pitch_box")
        self.horizontalLayout_2.addWidget(self.pitch_box)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.pitch_current = QtWidgets.QLabel(self.centralwidget)
        self.pitch_current.setObjectName("pitch_current")
        self.horizontalLayout_2.addWidget(self.pitch_current)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.roll_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.roll_box.setMinimum(-90.0)
        self.roll_box.setMaximum(90.0)
        self.roll_box.setObjectName("roll_box")
        self.horizontalLayout_3.addWidget(self.roll_box)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.roll_current = QtWidgets.QLabel(self.centralwidget)
        self.roll_current.setObjectName("roll_current")
        self.horizontalLayout_3.addWidget(self.roll_current)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.heading_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.heading_box.setMaximum(359.99)
        self.heading_box.setProperty("value", 278.0)
        self.heading_box.setObjectName("heading_box")
        self.horizontalLayout_4.addWidget(self.heading_box)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.heading_current = QtWidgets.QLabel(self.centralwidget)
        self.heading_current.setObjectName("heading_current")
        self.horizontalLayout_4.addWidget(self.heading_current)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.altitude_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.altitude_box.setMaximum(100000.0)
        self.altitude_box.setProperty("value", 1000.0)
        self.altitude_box.setObjectName("altitude_box")
        self.horizontalLayout_5.addWidget(self.altitude_box)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.altitude_current = QtWidgets.QLabel(self.centralwidget)
        self.altitude_current.setObjectName("altitude_current")
        self.horizontalLayout_5.addWidget(self.altitude_current)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.airspeed_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.airspeed_box.setMaximum(2000.0)
        self.airspeed_box.setProperty("value", 200.0)
        self.airspeed_box.setObjectName("airspeed_box")
        self.horizontalLayout_6.addWidget(self.airspeed_box)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.airspeed_current = QtWidgets.QLabel(self.centralwidget)
        self.airspeed_current.setObjectName("airspeed_current")
        self.horizontalLayout_6.addWidget(self.airspeed_current)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_12.addWidget(self.label_21)
        self.latitude_current = QtWidgets.QLabel(self.centralwidget)
        self.latitude_current.setObjectName("latitude_current")
        self.horizontalLayout_12.addWidget(self.latitude_current)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_13.addWidget(self.label_24)
        self.longitude_current = QtWidgets.QLabel(self.centralwidget)
        self.longitude_current.setObjectName("longitude_current")
        self.horizontalLayout_13.addWidget(self.longitude_current)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_15.addWidget(self.label_22)
        self.latitude_waypoint = QtWidgets.QLabel(self.centralwidget)
        self.latitude_waypoint.setObjectName("latitude_waypoint")
        self.horizontalLayout_15.addWidget(self.latitude_waypoint)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_15.addWidget(self.label_25)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_16.addWidget(self.label_27)
        self.longitude_waypoint = QtWidgets.QLabel(self.centralwidget)
        self.longitude_waypoint.setObjectName("longitude_waypoint")
        self.horizontalLayout_16.addWidget(self.longitude_waypoint)
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_16.addWidget(self.label_28)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        PilSim.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PilSim)
        self.statusbar.setObjectName("statusbar")
        PilSim.setStatusBar(self.statusbar)

        self.retranslateUi(PilSim)
        QtCore.QMetaObject.connectSlotsByName(PilSim)

    def retranslateUi(self, PilSim):
        _translate = QtCore.QCoreApplication.translate
        PilSim.setWindowTitle(_translate("PilSim", "War Thunder PilSim"))
        self.waypoint_file_enable.setText(_translate("PilSim", "Use Waypoint File"))
        self.waypoint_file_button.setText(_translate("PilSim", "Waypoint File:"))
        self.log_file_enable.setText(_translate("PilSim", "Use Log File"))
        self.log_file_button.setText(_translate("PilSim", "Log File:"))
        self.label.setText(_translate("PilSim", "Telemetry Sample Rate (Hz):"))
        self.label_8.setText(_translate("PilSim", "PC --> Arduino Port:"))
        self.refresh_ports.setText(_translate("PilSim", "Refresh Ports"))
        self.label_18.setText(_translate("PilSim", "PC <-- Arduino Port:"))
        self.refresh_ports_2.setText(_translate("PilSim", "Refresh Ports"))
        self.pilsim_enable.setText(_translate("PilSim", "Engage PilSim"))
        self.label_2.setText(_translate("PilSim", "Pitch:"))
        self.label_7.setText(_translate("PilSim", "Current:"))
        self.pitch_current.setText(_translate("PilSim", "0"))
        self.label_17.setText(_translate("PilSim", "°"))
        self.label_3.setText(_translate("PilSim", "Roll:"))
        self.label_10.setText(_translate("PilSim", "Current:"))
        self.roll_current.setText(_translate("PilSim", "0"))
        self.label_15.setText(_translate("PilSim", "°"))
        self.label_4.setText(_translate("PilSim", "Heading:"))
        self.label_12.setText(_translate("PilSim", "Current:"))
        self.heading_current.setText(_translate("PilSim", "0"))
        self.label_13.setText(_translate("PilSim", "°"))
        self.label_5.setText(_translate("PilSim", "Altitude:"))
        self.label_14.setText(_translate("PilSim", "Current:"))
        self.altitude_current.setText(_translate("PilSim", "0"))
        self.label_11.setText(_translate("PilSim", "m"))
        self.label_6.setText(_translate("PilSim", "Airspeed:"))
        self.label_16.setText(_translate("PilSim", "Current:"))
        self.airspeed_current.setText(_translate("PilSim", "0"))
        self.label_9.setText(_translate("PilSim", "kph"))
        self.label_21.setText(_translate("PilSim", "Latitude:"))
        self.latitude_current.setText(_translate("PilSim", "0"))
        self.label_23.setText(_translate("PilSim", "°"))
        self.label_24.setText(_translate("PilSim", "Longitude:"))
        self.longitude_current.setText(_translate("PilSim", "0"))
        self.label_26.setText(_translate("PilSim", "°"))
        self.label_22.setText(_translate("PilSim", "Waypoint Latitude:"))
        self.latitude_waypoint.setText(_translate("PilSim", "0"))
        self.label_25.setText(_translate("PilSim", "°"))
        self.label_27.setText(_translate("PilSim", "Waypoint Longitude:"))
        self.longitude_waypoint.setText(_translate("PilSim", "0"))
        self.label_28.setText(_translate("PilSim", "°"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PilSim = QtWidgets.QMainWindow()
    ui = Ui_PilSim()
    ui.setupUi(PilSim)
    PilSim.show()
    sys.exit(app.exec_())
